# This is a basic workflow to help you get started with Actions

name: Build Kernel Package

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build script
        id: build
        run: |
          mkdir /tmp/artifacts
          VERSION=$(grep ^KERNEL_VERSION build.sh | head -n1| cut -d = -f2)
          REL=$(grep "PKGREL=\d*" build.sh | cut -d = -f2)
          #REL=$( git tag |grep -F $VERSION|sort -r|head -n1|tr -d v)
          echo Building $VERSION-$REL
          echo "::set-output name=tag::${VERSION}-${REL}"
          sudo ./build.sh
          cd /tmp/artifacts
          ls -l
          dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
          ls -l
          
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-mbp-16x-wifi-${{ steps.build.outputs.tag }}
          path: /tmp/artifacts/*

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /tmp/artifacts/Packages.gz
            /tmp/artifacts/sha256
            /tmp/artifacts/*.deb
          tag_name: v${{ steps.build.outputs.tag }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

